info:
  name: Delete
  type: http
  seq: 4

http:
  method: delete
  url: "{{base_url}}/api/task/ddd79aae-4058-4537-9525-c64799009b59"
  headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZjUzY2I5NS1mNmY3LTRkZjQtOTQ4ZC0xNDMyZmE5MDkwNDEiLCJvcmdfaWQiOiI2MGU4Yjc0MS1iOWJlLTQ0NDUtYjE2My0wZTBlYzg4NmU5MGYiLCJyb2xlIjoiTUFOQUdFUiIsImV4cCI6MTc4MDEzODUxOX0.JGYvAB6AXN32fH1gGtXGy1MT2zcynV1oeH7tvgJAkoI
    - name: Accept
      value: application/json
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Invalid Token
    request:
      url: "{{base_url}}/api/task/ddd79aae-4058-4537-9525-c64799009b59"
      method: delete
      headers:
        - name: Authorization
          value: Bearer YOUR_ACCESS_TOKEN
        - name: Accept
          value: application/json
    response:
      status: 401
      statusText: Unauthorized
      headers:
        - name: date
          value: Sat, 30 May 2026 08:54:03 GMT
        - name: server
          value: uvicorn
        - name: content-length
          value: "69"
        - name: content-type
          value: application/json
      body:
        type: json
        data: |-
          {
            "status": 401,
            "code": "UNAUTHORIZED",
            "message": "Invalid access token"
          }
  - name: Invalid Role
    request:
      url: "{{base_url}}/api/task/ddd79aae-4058-4537-9525-c64799009b59"
      method: delete
      headers:
        - name: Authorization
          value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOTQ3ZjU2Yi00ZWViLTRmNzQtYTQyOS1kZjMwNmRjYzQ0YTQiLCJvcmdfaWQiOiI2MGU4Yjc0MS1iOWJlLTQ0NDUtYjE2My0wZTBlYzg4NmU5MGYiLCJyb2xlIjoiTUVNQkVSIiwiZXhwIjoxNzgwMTM4NDY3fQ.gyK5ME1gAY66LD68lX76j9I3aILmRLsniyygsZzyAVw
        - name: Accept
          value: application/json
    response:
      status: 403
      statusText: Forbidden
      headers:
        - name: date
          value: Sat, 30 May 2026 08:54:41 GMT
        - name: server
          value: uvicorn
        - name: content-length
          value: "119"
        - name: content-type
          value: application/json
      body:
        type: json
        data: |-
          {
            "detail": {
              "status": 403,
              "code": "FORBIDDEN",
              "message": "Role 'MEMBER' does not have permission to access this resource"
            }
          }
  - name: Success
    request:
      url: "{{base_url}}/api/task/ddd79aae-4058-4537-9525-c64799009b59"
      method: delete
      headers:
        - name: Authorization
          value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZjUzY2I5NS1mNmY3LTRkZjQtOTQ4ZC0xNDMyZmE5MDkwNDEiLCJvcmdfaWQiOiI2MGU4Yjc0MS1iOWJlLTQ0NDUtYjE2My0wZTBlYzg4NmU5MGYiLCJyb2xlIjoiTUFOQUdFUiIsImV4cCI6MTc4MDEzODUxOX0.JGYvAB6AXN32fH1gGtXGy1MT2zcynV1oeH7tvgJAkoI
        - name: Accept
          value: application/json
    response:
      status: 200
      statusText: OK
      headers:
        - name: date
          value: Sat, 30 May 2026 08:55:31 GMT
        - name: server
          value: uvicorn
        - name: content-length
          value: "69"
        - name: content-type
          value: application/json
      body:
        type: json
        data: |-
          {
            "status_code": 200,
            "message": "Task deleted successfully",
            "data": null
          }
